/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KitGrid {
        "container": boolean;
        "item": boolean;
        "spacing": number;
        "width": number;
    }
}
declare global {
    interface HTMLKitGridElement extends Components.KitGrid, HTMLStencilElement {
    }
    var HTMLKitGridElement: {
        prototype: HTMLKitGridElement;
        new (): HTMLKitGridElement;
    };
    interface HTMLElementTagNameMap {
        "kit-grid": HTMLKitGridElement;
    }
}
declare namespace LocalJSX {
    interface KitGrid {
        "container"?: boolean;
        "item"?: boolean;
        "spacing"?: number;
        "width"?: number;
    }
    interface IntrinsicElements {
        "kit-grid": KitGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kit-grid": LocalJSX.KitGrid & JSXBase.HTMLAttributes<HTMLKitGridElement>;
        }
    }
}
